services:
  redis:
    image: redis:alpine
    container_name: crash_redis_local
    # Ovo otvara port na tvom Windowsu da Node.js može da mu pristupi
    ports:
      - "6379:6379"
    # Ovo čuva podatke (ako ugasiš komp, da ne izgubiš keširane tikete)
    volumes:
      - ./redis_data:/data
    # Komanda za pokretanje sa čuvanjem podataka
    command: redis-server --appendonly yes
    restart: always